name: Controller Firmware CI

on:
  push:
  pull_request:

jobs:
  build-controller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ESP-IDF project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32p4
          path: firmware/controllerMain

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: controller-build
          path: |
            src/firmware/controller/build/*.bin
            src/firmware/controller/build/*.elf
            src/firmware/controller/build/bootloader/*.bin
            src/firmware/controller/build/partition_table/*.bin
